# base image
FROM node:12.2.0 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@latest

# add app
COPY . /app

# generate build
# ARG configuration=staging
RUN node --max_old_space_size=2048 ./node_modules/@angular/cli/bin/ng build --output-path=dist
RUN npm run post-build

# base image
FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 3000
EXPOSE 3000

# run nginx
CMD ["nginx", "-g", "daemon off;"]
